# Site
name: 'Samantha Writer'
title: 'Samantha Writer'
description: '10년차 콘텐츠 라이터 사만다의 글쓰기 블로그. AI 콘텐츠, 생산성, 기자 커리어 이야기를 다룹니다.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'https://samantha-writer.github.io'
google_analytics: 'G-62G444T2KR'
disqus: 'http-samantha-writer-github-io'

include: ["_pages"]
permalink: /blog/:title

# Authors
authors:
  samantha:
    name: Samantha
    display_name: Samantha Lee
    avatar: 'assets/images/samantha_avator.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: samantha.writer89@gmail.com
    web: https://samantha-writer.github.io
    instagram: https://www.instagram.com/samantha.writer
    description: "10년차 글쟁이. 경제지와 뉴미디어에서 기자로 일하다, 현재 IT 기업에서 인공지능 콘텐츠를 쓰고 있다. 취미로 생산성 앱을 활용한 글쓰기 프로세스를 연구한다."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

# Adsense
adsense: "disabled"

# Lazy Images
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor, .bundle, .backups]

# Jekyll Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
